spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/mancala
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: none

server:
  port: '8080'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html
  pathsToMatch: /api/game/**


game:
  stones:
    count: 4
